export const APP_INCREMENT_APISTACK = "APP_INCREMENT_APISTACK";
export const APP_DECREMENT_APISTACK = "APP_DECREMENT_APISTACK";
export const APP_ADD_NEXT_URL = "APP_ADD_NEXT_URL";
export const APP_CLEAR_NEXT_URL = "APP_CLEAR_NEXT_URL";

export const GAME_SET_PLAYER_NAME = "GAME_SET_PLAYER_NAME";
export const GAME_SET_PIN = "GAME_SET_PIN";