filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~
  - drop_event:
      when:
        or:
          - equals:
              container.name: "filebeat"
          - equals:
              container.name: "logstash"

multiline.pattern: (^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[\sz])|(^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*)
multiline.negate: true
multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]
